# Generated by Django 3.2 on 2023-05-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='shop', verbose_name='Картинка товар')),
                ('description', models.CharField(max_length=9999999, verbose_name='Описание товара')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
            ],
        ),
    ]
